---
name: WebService-YouTube
version: v1.0.1
author:
  - 'Hironori Yoshida <yoshida@cpan.org>'
abstract: Perl interfece to YouTube
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::Accessor::Fast: 0
  HTTP::Date: 0
  LWP::UserAgent: 0
  URI::Escape: 0
  XML::Simple: 0
  version: 0
provides:
  WebService::YouTube:
    file: lib/WebService/YouTube.pm
    version: v1.0.1
  WebService::YouTube::Feeds:
    file: lib/WebService/YouTube/Feeds.pm
    version: v1.0.1
  WebService::YouTube::User:
    file: lib/WebService/YouTube/User.pm
    version: v1.0.1
  WebService::YouTube::Util:
    file: lib/WebService/YouTube/Util.pm
    version: v1.0.1
  WebService::YouTube::Video:
    file: lib/WebService/YouTube/Video.pm
    version: v1.0.1
  WebService::YouTube::Videos:
    file: lib/WebService/YouTube/Videos.pm
    version: v1.0.1
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
