abstract: Perl interfece to YouTube
author: Hironori Yoshida C<< <yoshida@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.630
license: perl
name: WebService-YouTube
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  LWP::Simple: 0
  XML::Simple: 0
  version: 0
version: 0.01
